apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: demo:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: application-spring-cfg
              mountPath: /deployment/conf
      volumes:
        - name: application-spring-cfg
          configMap:
            name: demo-configmap
            items:
              - key: application.properties
                path: application.properties